routes/web.php
<?php

use App\Http\Controllers\LanguageController;

Route::get('lang/{lang}', [LanguageController::class, 'swap']);

Route::group(['namespace' => 'Frontend', 'as' => 'frontend.'], function () {
    include_route_files(__DIR__.'/frontend/');
});

Route::group(['namespace' => 'Backend', 'prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'access.routeNeedsPermission:view-backend'], function () {
    
    Route::redirect('/', '/admin/dashboard', 301);
    
    Route::group([
        'prefix' => 'auth', 
        'as' => 'auth.',
        'namespace' => 'Auth'
    ], function () {
        // User Management
        Route::group(['namespace' => 'User'], function () {
            // For DataTables
            Route::post('user/get', 'UserTableController')->name('user.get');
    
            // User Status'
            Route::get('user/deactivated', 'UserStatusController@getDeactivated')->name('user.deactivated');
            Route::get('user/deleted', 'UserStatusController@getDeleted')->name('user.deleted');
    
            // User CRUD
            Route::get('user', 'UserController@index')->name('user.index');
            Route::get('user/create', 'UserController@create')->name('user.create');
            Route::post('user',  'UserController@store')->name('user.store');
    
            // Specific User
            Route::group(['prefix' => 'user/{user}'], function () {
                // User
                Route::get('/', 'UserController@show')->name('user.show');
                Route::get('edit', 'UserController@edit')->name('user.edit');
                Route::patch('/', 'UserController@update')->name('user.update');
                Route::delete('/', 'UserController@destroy')->name('user.destroy');
    
                // Account
                Route::get('account/confirm/resend', 'UserConfirmationController@sendConfirmationEmail')->name('user.account.confirm.resend');
    
                // Status
                Route::get('mark/{status}', 'UserStatusController@mark')->name('user.mark')->where(['status' => '[0,1]']);
    
                // Social
                Route::delete('social/{social}/unlink', 'UserSocialController@unlink')->name('user.social.unlink');
    
                // Confirmation
                Route::get('confirm', 'UserConfirmationController@confirm')->name('user.confirm');
                Route::get('unconfirm', 'UserConfirmationController@unconfirm')->name('user.unconfirm');
    
                // Password
                Route::get('password/change', 'UserPasswordController@edit')->name('user.change-password');
                Route::patch('password/change', 'UserPasswordController@update')->name('user.change-password.post');
    
                // log in as
                Route::get('login-as', 'UserAccessController@loginAs')->name('user.login-as');
    
                // Session
                Route::get('clear-session', 'UserSessionController@clearSession')->name('user.clear-session');
    
                // Deleted
                Route::delete('delete-permanently', 'UserStatusController@delete')->name('user.delete-permanently');
                Route::post('restore', 'UserStatusController@restore')->name('user.restore');
            });
        });
    
        // Role Management
        Route::group(['namespace' => 'Role'], function () {
            Route::get('role', 'RoleController@index')->name('role.index');
            Route::get('role/create', 'RoleController@create')->name('role.create');
            Route::post('role', 'RoleController@store')->name('role.store');
    
            Route::group(['prefix' => 'role/{role}'], function () {
                Route::get('edit', 'RoleController@edit')->name('role.edit');
                Route::patch('/', 'RoleController@update')->name('role.update');
                Route::delete('/', 'RoleController@destroy')->name('role.destroy');
            });
    
            // For DataTables
            Route::post('role/get', 'RoleTableController')->name('role.get');
        });
    
        // Permission Management
        Route::group(['namespace' => 'Permission'], function () {
            Route::resource('permission', 'PermissionsController', ['except' => ['show']]);
    
            //For DataTables
           Route::post('permission/get', 'PermissionTableController')->name('permission.get');
        });
    });
    

    Route::get('dashboard', 'DashboardController@index')->name('dashboard');
    Route::post('get-permission', 'DashboardController@getPermissionByRole')->name('get.permission');

    //For settings
    Route::group(['prefix' => 'settings'], function () {
        Route::group(['namespace' => 'Countries'], function () {
            $country_path = 'countries';  
            Route::resource($country_path, 'CountriesController', ['except' => ['show']]);
            Route::post($country_path.'/get', 'CountriesTableController')->name('countries.get');
        });
        Route::group(['namespace' => 'Cities'], function () {
            $city_path = 'cities';  
            Route::resource($city_path, 'CitiesController', ['except' => ['show']]);
            Route::post($city_path.'/get', 'CitiesTableController')->name('cities.get');
        });
        Route::group(['namespace' => 'Branches'], function () {
            $branch_path = 'branches';  
            Route::resource($branch_path, 'BranchesController', ['except' => ['show']]);
            Route::post($branch_path.'/get', 'BranchesTableController')->name('branches.get');
        });
        Route::group(['namespace' => 'Vendors'], function () {
            $vendor_path = 'vendors';  
            Route::resource($vendor_path, 'VendorsController', ['except' => ['show']]);
            Route::post($vendor_path.'/get',  'VendorsTableController')->name('vendors.get');
        });
        Route::group(['namespace' => 'Subvendors'], function () {
            $subvendor_path = 'subvendors';  
            Route::resource($subvendor_path, 'SubVendorsController', ['except' => ['show']]);
            // Route::post($subvendor_path.'/get', 'SubVendorsTableController')->name('subvendors.get');
        });
        Route::group(['namespace' => 'Currencies'], function () {
            $currencies_path = 'currencies';  
            Route::resource($currencies_path, 'CurrenciesController', ['except' => ['show']]);
            Route::post($currencies_path.'/get', 'CurrenciesTableController')->name('currencies.get');
        });
       
    });
    
    // For catalogs
    Route::group(['prefix' => 'catalogs'], function () {

        Route::group(['namespace' => 'Brands'], function () {
            $brand_path = 'brands';  
            Route::resource($brand_path, 'BrandsController', ['except' => ['show']]);
            Route::post($brand_path.'/get', 'BrandsTableController')->name('brands.get');            
        });
        Route::group(['namespace' => 'Models'], function () {
            $model_path = 'models';  
            Route::resource($model_path, 'ModelsController', ['except' => ['show']]);
            Route::post($model_path.'/get', 'ModelsTableController')->name('models.get');
        });
        Route::group(['namespace' => 'Series'], function () {
            $series_path = 'series';  
            Route::resource($series_path, 'SeriesController', ['except' => ['show']]);
            Route::post($series_path.'/get',  'SeriesTableController')->name('series.get');
        });
        Route::group(['namespace' => 'Attributes'], function () {
            $attributes_path = 'attributes';  
            Route::resource($attributes_path, 'AttributesController', ['except' => ['show']]);
            Route::post($attributes_path.'/get',  'AttributesTableController')->name('attributes.get');
        });

        
    });

    
    Route::group(['namespace' => 'Catalogs'], function () {
        $catalog_path = 'catalogs';  
        Route::resource($catalog_path, 'CatalogsController', ['except' => ['show']]);
        Route::post($catalog_path.'/get', 'CatalogsTableController')->name('catalogs.get');            
    });

    //For shipping
    Route::group(['prefix' => 'shipping'], function () {

        Route::group(['namespace' => 'Cargo'], function () {
            $cargo_path = 'cargo';  
            Route::resource($cargo_path, 'CargoController', ['except' => ['show']]);
            Route::post($cargo_path.'/get', 'CargoTableController')->name('cargo.get');
        });

        Route::group(['namespace' => 'Agent'], function () {
            $agent_path = 'agent';  
            Route::resource($agent_path, 'AgentController', ['except' => ['show']]);
            Route::post($agent_path.'/get', 'AgentTableController')->name('agent.get');
        });
    });    
    Route::group(['prefix' => 'ajax'], function () {
        Route::group(['namespace' => 'Common'], function () {
            Route::post('get-model', 'CommonController@index');
            Route::post('get-city', 'CommonController@getCity');
            Route::post('get-series', 'CommonController@getSerie');
            Route::get('get-attribute', 'CommonController@getAttribute');
            Route::post('get-branch', 'CommonController@getBranch');
        });
       

    });
    
    

    

    
    
    
    
    
});

app/Models/Cargo.php
<?php 
namespace App\Models;
use App\Models\Traits\ModelAttributes;
use App\Models\Traits\Attributes\CargoAttributes;
use Illuminate\Database\Eloquent\SoftDeletes;

class Cargo extends BaseModel
{
    use SoftDeletes,ModelAttributes,CargoAttributes;
    protected $table = 'cargo_mode';
    protected $guarded = array();
    protected $casts = [
        'status' => 'boolean',
    ];

    protected $appends = [
        'display_status',
    ];
}

app/Http/Controllers/Backend/Agent/AgentController.php
<?php
namespace App\Http\Controllers\Backend\Agent;

use App\Http\Controllers\Controller;
use App\Http\Traits\GetTrait;
use App\Http\Traits\CommonTrait;
use App\Http\Responses\RedirectResponse;
use App\Models\Agent;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;
use Auth;


class AgentController extends Controller
{
    use GetTrait,CommonTrait;

    public function __construct()
    {
        View::share('js', ['agent']);
    }
    
    public function index()
    {
        return view('backend.agent.index');
    }

    public function create()
    {
        return view('backend.agent.create');
    }

    public function store(Request $request)
    {
        $post = new Agent();

        $validator = $this->validateAgentForm($request);
      
        if ($validator->fails()) 
            return redirect()->back()->withInput()->withErrors($validator);

        
        $post = $this->GetAgentForm($post, $request);
        $post->created_by = Auth::id();

        if ($post->save()){
            return redirect()->back()->with("success","The agent was successfully created.");
        }

    }

    public function update(Request $request, $id)
    {

        $validator = $this->validateAgentForm($request, $id);
        

        if ($validator->fails()) 
            return redirect()->back()->withInput()->withErrors($validator);

       
        $post = Agent::find($id);

        $post = $this->GetAgentForm($post, $request);
        $post->updated_by = Auth::id();

        if ($post->save()){
            return redirect()->back()->with("success","The agent was successfully updated.");
        }
    }

    public function edit($id)
    {

        $this->data['edit_agent'] = Agent::find($id);
        $this->data['edit_id'] = $id;
        return view('backend.agent.create', $this->data);
    }

   

    public function destroy($id)
    {
        $agent = Agent::find($id);
        $agent->delete();
        return new RedirectResponse(route('admin.agent.index'), ['flash_success' => __('The agent was successfully deleted.')]);
    }

}

app/Http/Controllers/Backend/Agent/AgentTableController.php
<?php

namespace App\Http\Controllers\Backend\Agent;

use App\Http\Controllers\Controller;
use App\Models\Agent;
use DB;
use Yajra\DataTables\Facades\DataTables;

class AgentTableController extends Controller
{
    public function __invoke()
    {
        $queries = Agent::leftjoin('users', 'users.id', '=', 'agent.created_by')
                        ->select([
                            'agent.id',
                            'agent.name',
                            'agent.phone',
                            'agent.email',
                            'agent.address',
                            'agent.status',
                            'agent.created_at',
                            'users.first_name as created_by',
                        ]);
        
        
    	return Datatables::of($queries)
            ->filterColumn('status', function ($query, $keyword) {
                if (in_array(strtolower($keyword), ['active', 'inactive'])) {
                    $query->where('agent.status', (strtolower($keyword) == 'active') ? 1 : 0);
                }
            })
            ->filterColumn('created_by', function ($query, $keyword) {
                $query->whereRaw('users.first_name like ?', ["%{$keyword}%"]);
            })
            ->editColumn('status', function ($agent) {
                return $agent->status_label;
            })
            ->editColumn('created_at', function ($agent) {
                return $agent->created_at->toDateString();
            })
            ->addColumn('actions', function ($agent) {
                return $agent->action_buttons;
            })
            ->escapeColumns(['name'])
            ->make(true);
    }
}

app/Http/Controllers/Backend/Attributes/AttributesController.php
<?php
namespace App\Http\Controllers\Backend\Attributes;

use App\Http\Controllers\Controller;
use App\Http\Traits\GetTrait;
use App\Http\Traits\CommonTrait;
use App\Http\Responses\RedirectResponse;
use App\Models\Attribute;
use Illuminate\Support\Facades\View;
use Illuminate\Http\Request;
use Auth;


class AttributesController extends Controller
{
    use GetTrait,CommonTrait;

    public function __construct()
    {
        View::share('js', ['attributes']);
    }
    
    public function index()
    {
        return view('backend.attributes.index');
    }

    public function create()
    {
        return view('backend.attributes.create');
    }

    public function store(Request $request)
    {
        $post = new Attribute();

        $validator = $this->validateAttributeForm($request, 0);
      
        if ($validator->fails()) 
            return redirect()->back()->withInput()->withErrors($validator);

        if (Attribute::where('name', $request['name'])->first()) {
            return redirect()->back()->with("error",'Attribute name already exist.');
        }

        $post = $this->GetCountryForm($post, $request);
        $post->created_by = Auth::id();

        if ($post->save()){
            return redirect()->back()->with("success","The attribute was successfully created.");
        }

    }

    public function update(Request $request, $id)
    {

        $validator = $this->validateAttributeForm($request, $id);
        

        if ($validator->fails()) 
            return redirect()->back()->withInput()->withErrors($validator);

        if (Attribute::where('name', $request['name'])->where('id', '!=', $id)->first()) {
            return redirect()->back()->with("success",'Attribute name already exist.');
        }

        $post = Attribute::find($id);

        $post = $this->GetCountryForm($post, $request);
        $post->updated_by = Auth::id();

        if ($post->save()){
            return redirect()->back()->with("success","The attribute was successfully updated.");
        }
    }

    public function edit($id)
    {
        $this->data['edit_attribute'] = Attribute::find($id);
        $this->data['edit_id'] = $id;
        return view('backend.attributes.create', $this->data);
    }

   

    public function destroy($id)
    {
        $attribute = Attribute::find($id);
        $attribute->delete();
        return new RedirectResponse(route('admin.attributes.index'), ['flash_success' => __('The attribute was successfully deleted.')]);
    }
    

}

app/Http/Controllers/Backend/Attributes/AttributesTableController.php
<?php

namespace App\Http\Controllers\Backend\Attributes;

use App\Http\Controllers\Controller;
use App\Models\Attribute;
use DB;
use Yajra\DataTables\Facades\DataTables;

class AttributesTableController extends Controller
{
    public function __invoke()
    {
        $queries = Attribute::leftjoin('users', 'users.id', '=', 'attributes.created_by')
                        ->select([
                            'attributes.id',
                            'attributes.name',
                            'attributes.status',
                            'attributes.created_at',
                            'users.first_name as created_by',
                        ]);
        
        
    	return Datatables::of($queries)
            ->filterColumn('status', function ($query, $keyword) {
                if (in_array(strtolower($keyword), ['active', 'inactive'])) {
                    $query->where('attributes.status', (strtolower($keyword) == 'active') ? 1 : 0);
                }
            })
            ->filterColumn('created_by', function ($query, $keyword) {
                $query->whereRaw('users.first_name like ?', ["%{$keyword}%"]);
            })
            ->editColumn('status', function ($attribute) {
                return $attribute->status_label;
            })
            ->editColumn('created_at', function ($attribute) {
                return $attribute->created_at->toDateString();
            })
            ->addColumn('actions', function ($attribute) {
                return $attribute->action_buttons;
            })
            ->escapeColumns(['name'])
            ->make(true);
    }
}

resources/views/backend/cargo/create.blade.php
@extends('backend.layouts.app')

@section('title', __('labels.backend.access.cargo.management') . ' | ' . __('labels.backend.access.cargo.create'))

@section('breadcrumb-links')
    @include('backend.cargo.includes.breadcrumb-links')
@endsection

@section('content')

@include('common.alert')

    @if(isset($edit_id))
        {{ Form::model($edit_id, ['route' => ['admin.cargo.update', $edit_id], 'method' => 'patch']) }}
    @else
        {{ Form::open(['route' => 'admin.cargo.store']) }}
    @endif

    <div class="card">
        <div class="card-body">
            <div class="row">
                <div class="col-sm-5">
                    <h4 class="card-title mb-0">
                        {{ __('labels.backend.access.cargo.management') }}
                        @if(isset($edit_id))
                        <small class="text-muted">{{ __('labels.backend.access.cargo.edit') }}</small>
                        @else
                        <small class="text-muted">{{ __('labels.backend.access.cargo.create') }}</small>
                        @endif
                    </h4>
                </div><!--col-->
            </div><!--row-->
        
            <hr>
        
            <div class="row mt-4 mb-4">
                
                <div class="col">
                    <div class="form-group row">
                        {{ Form::label('name', trans('validation.attributes.backend.access.cargo.name'), ['class' => 'col-md-2 from-control-label required']) }}
                        
                        <div class="col-md-10">
                            {{ Form::text('name', old('name',(isset($edit_cargo)) ? $edit_cargo->name:''),['class' => 'form-control' , 'placeholder' => trans('validation.attributes.backend.access.cargo.name')]) }}
                        </div><!--col-->
                    </div><!--form-group-->
                    
                    
        
                    <div class="form-group row">
                        {{ Form::label('status', trans('validation.attributes.backend.access.cargo.status'), ['class' => 'col-md-2 from-control-label required']) }}
        
                        
                        <div class="col-md-10">
                            <div class="checkbox d-flex align-items-center">
                                <label class="switch switch-label switch-pill switch-primary mr-2" for="role-1">
                                    <input class="switch-input" type="checkbox" name="status" id="role-1" value="1" 
                                        {{ (!isset($edit_cargo->status) ||(isset($edit_cargo->status) && $edit_cargo->status == 1)) ? "checked" : "" }}>
        
                                        <span class="switch-slider" data-checked="on" data-unchecked="off"></span>
                                </label>
                            </div>
                        </div><!--col-->
                    </div><!--form-group-->
                </div><!--col-->
            </div><!--row-->
        </div><!--card-body-->
        
        <div class="card-footer">
            <div class="row">
                <div class="col">
                    <a href="{{route('admin.cargo.index')}}" class="btn btn-danger btn-sm">Cancel</a>
                </div><!--col-->
        
                <div class="col text-right">
                    @if(isset($edit_id))
                    <input class="btn btn-success btn-sm pull-right" type="submit" value="UPDATE">
                    @else
                    <input class="btn btn-success btn-sm pull-right" type="submit" value="Create">
                    @endif
                </div><!--row-->
            </div><!--row-->
        </div>
    </div><!--card-->
    {{ Form::close() }}
@endsection

resources/views/backend/cargo/index.blade.php
@extends('backend.layouts.app')

@section('title', app_name() . ' | ' . __('labels.backend.access.cargo.management'))

@section('breadcrumb-links')
@include('backend.cargo.includes.breadcrumb-links')
@endsection

@section('content')
<div class="card">
    <div class="card-body">
        <div class="row">
            <div class="col-sm-5">
                <h4 class="card-title mb-0">
                    {{ __('labels.backend.access.cargo.management') }} <small class="text-muted">{{ __('labels.backend.access.cargo.active') }}</small>
                </h4>
            </div>
            <!--col-->
        </div>
        <!--row-->

        <div class="row mt-4">
            <div class="col">
                <div class="table-responsive">
                    <table id="cargo" class="table" data-ajax_url="{{ route("admin.cargo.get") }}">
                        <thead>
                            <tr>
                                <th>{{ trans('labels.backend.access.cargo.table.name') }}</th>
                                <th>{{ trans('labels.backend.access.cargo.table.status') }}</th>
                                <th>{{ trans('labels.backend.access.cargo.table.createdby') }}</th>
                                <th>{{ trans('labels.backend.access.cargo.table.createdat') }}</th>
                                <th>{{ trans('labels.general.actions') }}</th>
                            </tr>
                        </thead>
                        <tbody>
                        </tbody>
                    </table>
                </div>
            </div>
            <!--col-->
        </div>
        <!--row-->

    </div>
    <!--card-body-->
</div>
<!--card-->
@endsection

@section('pagescript')
<script>
    FTX.Utils.documentReady(function() {
        FTX.Cargo.list.init();
    });
</script>
@stop